---
title: "State deaths outliers"
author: "Delphi Group"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    code_folding: hide
params:
  window_size: 14
  start_date: 2020-04-01
  sig_cut: 2.5
---

```{r setup, warning=FALSE, message=FALSE}
library(covidcast)
library(dplyr)
#library(tidyverse)
library(lubridate)
library(RcppRoll)
library(cowplot)
library(ggplot2)
library(DT)
knitr::opts_chunk$set(warning = FALSE, message=FALSE)
window_size = params$window_size
start_date = params$start_date
sig_cut = params$sig_cut
```

Retrieve data for all states
```{r}
states <-  suppressMessages(
  covidcast_signal(
  "jhu-csse","deaths_incidence_num", 
  geo_type = "state", 
  start_day = start_date)
)

states <- states %>% group_by(geo_value) %>% mutate(
  fmean = roll_meanr(value, window_size),
  fsd = roll_sdr(value, window_size),
  smean = roll_mean(value, window_size, fill=NA),
  ssd = roll_sd(value, window_size, fill=NA),
  ssd = roll_sd(value, window_size, fill=NA),
  flag = abs(value-fmean)/fsd > sig_cut | abs(value-smean)/ssd > sig_cut
  
)
```


All-states plot matrix
```{r fig.height = 30, fig.width = 10}
states$geo_value <- as.factor(states$geo_value)

states %>%
  filter(any(flag == 'TRUE')) %>%
  ggplot(aes(time_value, value)) + 
    geom_line(aes(color="observed")) +
    geom_ribbon(aes(
      fill="filtered",
      ymin=fmean-sig_cut*fsd, 
      ymax=fmean+sig_cut*fsd), alpha=.25) +
    geom_ribbon(aes(
      fill="smoothed",
      ymin=smean-sig_cut*ssd, 
      ymax=smean+sig_cut*ssd), alpha=.25) +
    geom_line(aes(y=fmean, color="filtered")) + 
    geom_line(aes(y=smean, color="smoothed")) +
    geom_point(data=filter(states, flag), aes(color="outliers")) +
    facet_wrap(.~geo_value,nrow=30,scales = 'free_y') + 
    theme_cowplot() + xlab("date") + 
    ylab(attributes(states)$metadata$signal) +
    scale_fill_manual(breaks=c("filtered","smoothed"), 
                      values=c("blue","darkgreen"))+
    scale_color_manual(
      breaks=c("observed", "filtered","smoothed","outliers"),
      values = c("black", "blue","darkgreen","red"))
```

Output the outliers

```{r}
outliers <- outlier <- states %>% group_by(geo_value) %>% filter(flag == 'TRUE') %>%
 select(geo_value,signal,time_value, value, fmean, fsd, smean, ssd)

datatable(outlier,options = list(scrollX = TRUE, scrollY = "300px",paging = FALSE),rownames = NULL) %>% formatSignif(~fmean+fsd+smean+ssd,3)

```








