---
title: "Facebook Survey Dashboard"
author: "Delphi Group"
output:
  flexdashboard::flex_dashboard:
    social: menu
    source_code: embed
    vertical_layout: fill
---

```{r setup, include=FALSE, cache=TRUE, autodep=TRUE}
library(covidcast)
library(dplyr)
library(tidyr)
library(ggplot2)
library(flexdashboard)
knitr::opts_chunk$set(cache=TRUE, autodep=TRUE)

df_fb1_st = covidcast_signal("fb-survey", "raw_cli", geo_type = "state")
n_per_day = df_fb1_st %>% 
  group_by(time_value) %>% 
  summarize("Number of responses" = sum(sample_size)) 

df_fb1 = covidcast_signal("fb-survey", "smoothed_cli")
county_per_week = df_fb1 %>% 
  group_by(time_value) %>%
  summarize("Number of counties" = n())

ts_views = inner_join(n_per_day, county_per_week) %>%
  pivot_longer(-time_value)

county_totals = df_fb1 %>% 
  group_by(geo_value) %>%
  summarize(value = n()) %>% ungroup() %>%
  filter(substr(geo_value,3,5) != "000") 

county_totals$time_value = "2020-04-15"
county_totals$issue = "2020-04-15"
attributes(county_totals)$geo_type = "county"
class(county_totals) = c("covidcast_signal", "data.frame")

df_fb2 = covidcast_signal("fb-survey", "smoothed_hh_cmnty_cli")
df_in = covidcast_signal("jhu-csse", "confirmed_7dav_incidence_prop", 
                         start_day = min(df_fb1$time_value))

case_num = 500
geo_values = covidcast_signal("jhu-csse", "confirmed_cumulative_num",
                              max(df_in$time_value), max(df_in$time_value)) %>%
  filter(value >= case_num) %>% pull(geo_value)
df_fb1_act = df_fb1 %>% filter(geo_value %in% geo_values)
df_fb2_act = df_fb2 %>% filter(geo_value %in% geo_values)
df_in_act = df_in %>% filter(geo_value %in% geo_values)

df_cor1 = covidcast_cor(df_fb1_act, df_in_act, by = "time_value",
                        method = "spearman")
df_cor2 = covidcast_cor(df_fb2_act, df_in_act, by = "time_value",
                        method = "spearman")

df_cor = bind_rows("% CLI" = df_cor1, "% CLI-in-community"=df_cor2, .id="signal")
```

Sampling
=====================

Column 
-----------------

```{r, message = FALSE, warning = FALSE, fig.width=10, fig.height=6}
ggplot(ts_views, aes(time_value, value)) +
  geom_line() + geom_point() + theme_bw() +
  labs(x="Date", y="")+
  facet_wrap(~name, nrow=2, scales="free_y")
```

Column
------------------

```{r}
total_responses = round(sum(n_per_day$`Number of responses`))
mean_daily = round(mean(n_per_day$`Number of responses`))
unique_counties = length(unique(df_fb1$geo_value))
mean_week = round(mean(county_per_week$`Number of counties`))
```

### Total responses
```{r}
valueBox(total_responses)
```

### Mean daily responses
```{r}
valueBox(mean_daily)
```

### Number of unique counties
```{r}
valueBox(unique_counties)
```

### Mean unique counties per week
```{r}
valueBox(mean_week)
```


Coverage map
======


```{r, message = FALSE, warning = FALSE}
plot(county_totals, title = "Which counties ever appear in our CLI signals?",
     choro_col = c("#D3D3D3", "#FFC0CB"), choro_params = list(breaks = c(0, 1), 
                                                              legend_width = 5))
```

Correlations
=====================


```{r, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5}
ggplot(df_cor, aes(x = time_value, y = value)) + 
  geom_line(aes(color = signal)) + 
  labs(title = "Correlation between CLI signals and cases",
       subtitle = sprintf("Over all counties with at least %i cases", case_num),
       x = "Date", y = "Correlation") + theme_bw() +
  theme(legend.position = "bottom", legend.title  = element_blank())
```
